spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/authServiceFallback

        - id: beverage
          uri: lb://beverage-service
          predicates:
            - Path=/beverage-service/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: beverageCircuitBreaker
                fallbackUri: forward:/beverageServiceFallback

        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/orderServiceFallback
