# closed - UP
# open - DOWN
# half-open - UNKNOWN

# Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      external:
        sliding-window-size: 10
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        allow-health-indicator-to-fail: true
        register-health-indicator: true

## Kafka Producer Configuration:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: orderConfirmationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:com.infybuzz.event.OrderConfirmationEvent

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8083/api/auth
          jwk-set-uri: http://localhost:8083/api/auth/.well-known/jwks.json