logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: beverage
          uri: lb://beverage-service
          predicates:
            - Path=/api/beverage/**

        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8083/api/auth
          jwk-set-uri: http://localhost:8083/api/auth/.well-known/jwks.json   # To retrieve the public key corresponding tp the kid in JWT